In [1]:
import numpy as np

In [12]:
# Your task is to use np.loadtxt() function to load the data into a variable. 
# Answer:
matrix = np.loadtxt('diabetes.csv',skiprows = 1,delimiter = ',')


In [13]:
matrix

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [16]:
# How many patients does the dataset have information about?
matrix.shape

(768, 9)

In [18]:
# What is the blood pressure of the patient number 5 (0-indexed)?
matrix[5,2]

74.0

In [19]:
# What is the age of the patient number 112 (0-indexed)?
matrix[112,-2]

23.0

In [20]:
# In this dataset, Outcome = 0 denotes that the patient does not have diabetes. 
# And Outcome = 1 denotes that the patient has diabetes.

# Does patient number 227 (0-indexed) have diabetes?
matrix[227,-1]

1.0

In [30]:
# Out of the 768 patients total, how many have diabetes?
cnt = 0
outcome = matrix[:,-1]
for v in outcome:
    if v == 1:
        cnt+=1
print(cnt)

268


In [33]:
# For features Glucose, BloodPressure, SkinThickness, Insulin and BMI 
# (columns 1, 2, 3, 4 and 5 0-indexed) the values are missing for some of the patients. 
# Instead of the actual value, the dataset simply has a 0.

# For how many patients is the Insulin value missing?
missing_insulin = sum(matrix[:,4]==0)
print(missing_insulin)

374


In [42]:
# For how many patients is at-least one of the features missing?
# (Be careful that it is okay for someone to be Pregnant 0 times).
print(
  sum( 
    (matrix[:, 1] == 0) | 
    (matrix[:, 2] == 0) | 
    (matrix[:, 3] == 0) | 
    (matrix[:, 4] == 0) | 
    (matrix[:, 5] == 0) | 
    (matrix[:, 6] == 0) | 
    (matrix[:, 7] == 0) 
  )
)

376


In [58]:
# Filter out the dataset so that only the patients who don't have any data missing remain.
# You might find the np.logical_not() function useful. Verify that the shape of
# the resulting matrix is (392, 9).

# For all future questions, use the filtered data.

# failed attempts:
# data = filter(np.logical_not(matrix),matrix)
bad = ( 
    (matrix[:, 1] == 0) | 
    (matrix[:, 2] == 0) |
    (matrix[:, 3] == 0) |
    (matrix[:, 4] == 0) |
    (matrix[:, 5] == 0) |
    (matrix[:, 6] == 0) |
    (matrix[:, 7] == 0)
)
data = matrix[np.logical_not(bad), :]
print(data.shape)

(392, 9)


In [59]:
# Out of the 392 patients, what is the total number of patients
# who have diabetes in the filtered dataset?
print(sum(data[:,-1]))

130.0


In [62]:
# What is the average glucose level in the filtered dataset?
np.mean(data[:,1])

122.62755102040816

In [66]:
# What is the average glucose level among the diabetes patients?
diabetic = data[ (data[:, 8] == 1) , :]
ans = np.mean(diabetic, axis=0)
print(ans)

[  4.46923077 145.19230769  74.07692308  32.96153846 206.84615385
  35.77769231   0.62558462  35.93846154   1.        ]


In [72]:
print(diabetic)

[[0.000e+00 1.370e+02 4.000e+01 ... 2.288e+00 3.300e+01 1.000e+00]
 [3.000e+00 7.800e+01 5.000e+01 ... 2.480e-01 2.600e+01 1.000e+00]
 [2.000e+00 1.970e+02 7.000e+01 ... 1.580e-01 5.300e+01 1.000e+00]
 ...
 [3.000e+00 1.870e+02 7.000e+01 ... 4.080e-01 3.600e+01 1.000e+00]
 [0.000e+00 1.810e+02 8.800e+01 ... 2.220e-01 2.600e+01 1.000e+00]
 [1.000e+00 1.280e+02 8.800e+01 ... 1.057e+00 3.700e+01 1.000e+00]]


In [73]:
# ans is actually the  glucose level:
print(ans[1])
# The mean value was:
# 122.62755102040816

145.19230769230768


In [81]:
# What is the average glucose level among the non-diabetic people?
non_diabetic = data[data[:,-1] == 0,:]
ans = np.mean(non_diabetic,axis=0)[1]
ans

111.43129770992367